#version: '3.5'
services:
  db-postgresql:
    container_name: db-postgresql
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bdfinanceiro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-new-financeiro

volumes:
  pgdata:

networks:
  network-new-financeiro:
    driver: bridge