#version: '3.5'
services:
  db-postgresql:
    container_name: db-postgresql
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bdfinanceiro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-new-financeiro

  app-financeiro:
    container_name: app-financeiro
    build:
      context: .
      dockerfile: Dockerfile
    image: docjv/sis-financeiro:latest
    restart: always
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgresql:5432/bdfinanceiro
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db-postgresql
    networks:
      - network-new-financeiro

volumes:
  pgdata:

networks:
  network-new-financeiro:
    driver: bridge